name: Accessing the secrets
on:
  [push]
jobs:
  access-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Access Secrets
        env: 
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
            echo $OPENWEATHERMAP_API_KEY