name: Accessing the secrets
on:
  [push]
jobs:
  access-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Access Secrets
        env: 
          OPENWEATHERMAP_API_KEY: ${{secrets.OPENWEATHERMAP_API_KEY}}
        run: |
            echo $OPENWEATHERMAP_API_KEY
            echo $result
      - run: curl https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=${{secrets.OPENWEATHERMAP_API_KEY}}
      - run: curl https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=${{env.OPENWEATHERMAP_API_KEY}}