name: Accessing the secrets
on:
  [push]
jobs:
  access-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Access Secrets
        env: 
          apiKey: ${{secrets.OPENWEATHERMAP_API_KEY}}
        run: |
            echo $apiKey
            curl --location 'https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=${{env.OPENWEATHERMAP_API_KEY}}'
            curl --location 'https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=$apiKey'
      - run: curl --location 'https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=${{secrets.OPENWEATHERMAP_API_KEY}}'
      - run : |
              example-command "$secrets.OPENWEATHERMAP_API_KEY"
      
