name: Accessing the secrets
on:
  [push]
jobs:
  access-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Access Secrets
        run: curl --location 'https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=${{secrets.OPENWEATHERMAP_API_KEY}}'