name: Greeting on variable day
on:
  workflow_dispatch
env:
    MY_WORKFLOW_VARIABLE: "This is a work flow variable"
jobs:
  check-variable-scope:
    runs-on: ubuntu-latest
    env:
        MY_JOB_VARIABLE: 'This is a job flow variable'
    steps:
      - name: 'step1'
        run: |
            echo ${{env.MY_WORKFLOW_VARIABLE}}
            echo "$MY_JOB_VARIABLE"
            echo "$MY_STEP_VARIABLE"
        env:
            MY_STEP_VARIABLE: 'This is a step flow variable'